# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 657f7a9e3ba337b006c93ea9498656b758fcd130d212c276802e3be95a6a04a6a479d2810e9459e4ddbf4d32cbcd9c1593d9cc25bf8b914220f5cf70bef4bd11

test:
  secret_key_base: 68862cb900a2a2e71607a27d003a27a6b18dbb91f7811cfaefe7119419ff26a76e34986210e653729b45146bab6847b6c6fa28bc72f8ba9788862974b95f905f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
